# Generated by Django 4.2.4 on 2023-09-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Master',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default=1)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_master',
            },
        ),
        migrations.CreateModel(
            name='SaleMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('invoice_no', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_sale_mstr',
            },
        ),
        migrations.CreateModel(
            name='Supplier_Master',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.CharField()),
                ('status', models.CharField(default=1)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_supplier_master',
            },
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item_master')),
                ('sale_mstr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.salemaster')),
            ],
            options={
                'db_table': 'tbl_sale_details',
            },
        ),
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier_master')),
            ],
            options={
                'db_table': 'tbl_purchase_mstr',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item_master')),
                ('purchase_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchasemaster')),
            ],
            options={
                'db_table': 'tbl_purchase_details',
            },
        ),
    ]
