# Generated by Django 4.2.4 on 2023-09-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_master',
            old_name='item_id',
            new_name='id',
        ),
    ]
