# Generated by Django 4.2.4 on 2023-09-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_item_id_item_master_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_master',
            old_name='supplier_id',
            new_name='id',
        ),
    ]
