# Generated by Django 4.2.4 on 2023-09-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemmaster_supplier_alter_purchasedetail_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='invoice_date',
            field=models.DateField(),
        ),
    ]
